import {blank,Engine,safeUrl} from '../lib/engine';
import type {Store,LiveTab,Command,SavedTab} from '../types';
const KEY='squeeze.v1';
async function read():Promise<Store>{const s=(await chrome.storage.local.get(KEY))[KEY];if(!s)return blank();if(s.schemaVersion!==1||!Array.isArray(s.parked))throw new Error('Saved data needs a newer Squeeze version. Nothing was changed.');return s}
async function live():Promise<LiveTab[]>{const tabs=await chrome.tabs.query({});const groups=new Map<number,chrome.tabGroups.TabGroup>();try{for(const g of await chrome.tabGroups.query({}))groups.set(g.id,g)}catch{}return tabs.filter(t=>t.id!==undefined&&!t.incognito&&safeUrl(t.url)).map(t=>({id:t.id!,url:t.url!,title:t.title||t.url!,favicon:t.favIconUrl,windowId:t.windowId,index:t.index,pinned:t.pinned,active:t.active,group:groups.has(t.groupId)?{id:t.groupId,title:groups.get(t.groupId)!.title||'Untitled group',color:groups.get(t.groupId)!.color}:undefined}))}
const engine=new Engine({read,write:async s=>{await chrome.storage.local.set({[KEY]:s})},tabs:live,get:async id=>{const t=await chrome.tabs.get(id);return {id,url:t.url||'',title:t.title||'',windowId:t.windowId,index:t.index,pinned:t.pinned,incognito:t.incognito}},close:async id=>{await chrome.tabs.remove(id)},open:async(t,windowId)=>{const tab=await chrome.tabs.create({url:t.url,pinned:t.pinned,active:false,...(windowId?{windowId}:{})});return tab.id!},newWindow:async()=>{const w=await chrome.windows.create({focused:true});return w.id!},group:async(ids,g)=>{const id=await chrome.tabs.group({tabIds:ids});await chrome.tabGroups.update(id,{title:g.title,color:g.color})}});
function ids(value:unknown):asserts value is string[]{if(!Array.isArray(value)||!value.every(v=>typeof v==='string'))throw new Error('Invalid saved-tab selection')}
async function handle(c:Command){
 switch(c.type){
  case 'list':{const w=await chrome.windows.getLastFocused({windowTypes:['normal']});return {store:await read(),tabs:await live(),currentWindowId:w.id||0}}
  case 'squeeze':if(!Array.isArray(c.tabIds)||!c.tabIds.every(Number.isInteger))throw new Error('Invalid tab selection');return engine.squeeze([...new Set(c.tabIds)]);
  case 'reopen':ids(c.ids);return engine.reopen(c.ids,c.newWindow);
  case 'delete':ids(c.ids);return engine.mutate(s=>({...s,parked:s.parked.filter(t=>!c.ids.includes(t.id)),recent:s.recent.filter(t=>!c.ids.includes(t.id))}));
  case 'restore':if(!Array.isArray(c.records)||!c.records.every(t=>safeUrl(t.url)&&typeof t.id==='string'))throw new Error('Invalid restore data');return engine.mutate(s=>({...s,parked:[...c.records.filter(t=>!s.parked.some(p=>p.id===t.id)),...s.parked]}));
  case 'update':{ids(c.ids);return engine.mutate(s=>{const patch:Partial<SavedTab>={};if(typeof c.patch.starred==='boolean')patch.starred=c.patch.starred;if(c.patch.categoryId===null||s.categories.some(n=>n.id===c.patch.categoryId))patch.categoryId=c.patch.categoryId;if(c.patch.sessionId===null||s.sessions.some(n=>n.id===c.patch.sessionId))patch.sessionId=c.patch.sessionId;return {...s,parked:s.parked.map(t=>c.ids.includes(t.id)?{...t,...patch}:t)}})}
  case 'category':case 'session':{const key=c.type==='category'?'categories':'sessions';const field=c.type==='category'?'categoryId':'sessionId';const name=String(c.name||'').trim().slice(0,80);if(!c.remove&&!name)throw new Error('Choose a name');return engine.mutate(s=>({...s,[key]:c.remove?s[key].filter(n=>n.id!==c.id):c.id?s[key].map(n=>n.id===c.id?{...n,name}:n):[...s[key],{id:crypto.randomUUID(),name,createdAt:Date.now()}],parked:c.remove?s.parked.map(t=>t[field]===c.id?{...t,[field]:null}:t):s.parked}))}
  default:throw new Error('Unknown action');
 }
}
chrome.runtime.onMessage.addListener((c:Command,sender,reply)=>{if(sender.id!==chrome.runtime.id)return;handle(c).then(data=>reply({ok:true,data})).catch(e=>reply({ok:false,error:e.message||"Couldn't complete this action. Your saved tabs are safe."}));return true});
chrome.runtime.onInstalled.addListener(async()=>{await chrome.contextMenus.removeAll();chrome.contextMenus.create({id:'squeeze-tab',title:'Squeeze this tab',contexts:['page']});chrome.contextMenus.create({id:'squeeze-domain',title:'Squeeze similar tabs',contexts:['page']});chrome.contextMenus.create({id:'organize',title:'Organize in Squeeze',contexts:['page']});await cache()});
chrome.contextMenus.onClicked.addListener((info,t)=>{if(!t?.id||t.incognito)return;if(info.menuItemId==='organize'){void chrome.tabs.create({url:chrome.runtime.getURL('app.html')});return}void (async()=>{const tabs=await live();const chosen=info.menuItemId==='squeeze-domain'?tabs.filter(v=>new URL(v.url).hostname===new URL(t.url||'').hostname).map(v=>v.id):[t.id!];await engine.squeeze(chosen)})().catch(console.error)});
chrome.commands.onCommand.addListener((command,tab)=>{if(command==='open-squeeze'&&tab)void chrome.tabs.create({url:chrome.runtime.getURL('app.html')});if(command==='squeeze-current'&&tab?.id&&!tab.incognito)void engine.squeeze([tab.id]).catch(console.error)});
let caching:Promise<void>=Promise.resolve();
function cache(){caching=caching.then(async()=>{const tabs=await live();await chrome.storage.session.set({observed:tabs})}).catch(()=>{});return caching}
chrome.tabs.onCreated.addListener(()=>{void cache()});chrome.tabs.onUpdated.addListener(()=>{void cache()});chrome.tabs.onMoved.addListener(()=>{void cache()});
chrome.tabs.onRemoved.addListener((id)=>{void engine.serial(async()=>{const cached:LiveTab[]=(await chrome.storage.session.get('observed')).observed||[];const t=cached.find(v=>v.id===id);if(t&&safeUrl(t.url)&&!t.incognito){const s=await read();if(!s.parked.some(r=>r.sourceTabId===id&&r.url===t.url)){const {snapshot}=await import('../lib/engine');await chrome.storage.local.set({[KEY]:{...s,recent:[snapshot(t),...s.recent].slice(0,100)}})}}await cache()}).catch(console.error)});
void cache();
