import {useEffect,useState,useCallback,useRef} from 'react';
import {AnimatePresence,motion,useReducedMotion} from 'motion/react';
import {Archive,ArrowUpRight,Check,ChevronDown,Command,Folder,Layers,MoreHorizontal,PanelLeft,Plus,Search,SlidersHorizontal,Star,Trash2,X,Pin,RotateCcw,ExternalLink,Copy,CheckCircle2} from 'lucide-react';
import {domain,preview,request,searchTabs} from '../lib/client';
import type {Overview,SavedTab,LiveTab,Command as Cmd,Result} from '../types';
import {Mark} from './Mark';
type View='open'|'parked'|'starred'|'recent'|'sessions';
export function App(){
 const [data,setData]=useState<Overview>();const [view,setView]=useState<View>('parked');const [q,setQ]=useState('');const [filter,setFilter]=useState<string|null>(null);const [selected,setSelected]=useState<Set<string>>(new Set());const [busy,setBusy]=useState(false);const [status,setStatus]=useState('');const [error,setError]=useState('');const [palette,setPalette]=useState(false);const [undo,setUndo]=useState<SavedTab[]>([]);const [menu,setMenu]=useState<string|null>(null);const [dialog,setDialog]=useState<{type:'category'|'session';id?:string;name:string}|null>(null);const [help,setHelp]=useState(false);const reduced=useReducedMotion();const searchRef=useRef<HTMLInputElement>(null);
 const refresh=useCallback(async()=>{try{setData(await request<Overview>({type:'list'}))}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{void refresh();if(preview)return;const change=()=>void refresh();chrome.storage.onChanged.addListener(change);chrome.tabs.onCreated.addListener(change);chrome.tabs.onRemoved.addListener(change);chrome.tabs.onUpdated.addListener(change);return()=>{chrome.storage.onChanged.removeListener(change);chrome.tabs.onCreated.removeListener(change);chrome.tabs.onRemoved.removeListener(change);chrome.tabs.onUpdated.removeListener(change)}},[refresh]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(v=>!v)}if(e.key==='Escape'){setPalette(false);setMenu(null);setDialog(null);setHelp(false)}};addEventListener('keydown',onKey);return()=>removeEventListener('keydown',onKey)},[]);
 const choose=(v:View,f:string|null=null)=>{setView(v);setFilter(f);setSelected(new Set());setQ('')};
 async function act(c:Cmd,success?:string){if(busy)return;setBusy(true);setError('');setStatus(c.type==='squeeze'?'Saving your tabs, then closing...':'');try{const r=await request<Result>(c);setStatus(success||r?.message||'Done.');setSelected(new Set());await refresh()}catch(e){setError((e as Error).message);setStatus('')}finally{setBusy(false)}}
 function toggle(id:string){setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})}
 if(!data)return <main className="app loading"><Mark/><h2>{error?'Could not open Squeeze':'A little room to breathe.'}</h2><p>{error||'Loading your tabs...'}</p><button onClick={()=>void refresh()}>Try again</button></main>;
 const {store,tabs}=data;let saved=view==='recent'?store.recent:store.parked;if(view==='starred')saved=saved.filter(t=>t.starred);if(filter)saved=saved.filter(t=>t.categoryId===filter||t.sessionId===filter);saved=searchTabs(saved,q,store);
 const open=tabs.filter(t=>`${t.title} ${t.url}`.toLowerCase().includes(q.toLowerCase()));
 const count=view==='open'?open.length:saved.length;const title=view==='open'?'Open tabs':view==='starred'?'Starred':view==='recent'?'Recently closed':view==='sessions'?'Sessions':filter?(store.categories.concat(store.sessions).find(n=>n.id===filter)?.name||'Squeezed'):'Squeezed';
 const squeeze=(ids:number[])=>void act({type:'squeeze',tabIds:ids});
 const deleteTabs=(records:SavedTab[])=>{setUndo(records);void act({type:'delete',ids:records.map(t=>t.id)},`${records.length} saved ${records.length===1?'tab':'tabs'} removed.`)};
 const nav=[['open',PanelLeft,'Open tabs',tabs.length],['parked',Archive,'Squeezed',store.parked.length],['sessions',Layers,'Sessions',store.sessions.length],['starred',Star,'Starred',store.parked.filter(t=>t.starred).length],['recent',RotateCcw,'Recently closed',store.recent.length]] as const;
 return <main className={location.pathname.endsWith("app.html")?"app dashboard":"app"}>
 <header className="brand"><span className="brand-name"><Mark/>Squeeze</span><button className="icon-button" title="About Squeeze" aria-label="About Squeeze" onClick={()=>setHelp(true)}><SlidersHorizontal size={17}/></button></header>
 {preview&&<div className="preview">Design preview · Sample tabs, not your browser</div>}
 <button className="search-box" onClick={()=>setPalette(true)}><Search size={16}/><span>Find a tab or command</span><kbd>⌘ K</kbd></button>
 <nav className="nav" aria-label="Main navigation">{nav.map(([v,Icon,label,n])=><button key={v} className={view===v&&!filter?'nav-item active':'nav-item'} onClick={()=>choose(v)}><Icon size={17}/><span>{label}</span><span className="count">{n}</span></button>)}</nav>
 <section className="category-section"><div className="section-label">YOUR CATEGORIES<button className="icon-button" aria-label="Create category" onClick={()=>setDialog({type:'category',name:''})}><Plus size={15}/></button></div><div className="category-chips">{store.categories.map(c=><button key={c.id} className={filter===c.id?'chip chosen':'chip'} onClick={()=>choose('parked',c.id)}><span className="dot"/>{c.name}</button>)}{!store.categories.length&&<button className="chip muted" onClick={()=>setDialog({type:'category',name:''})}>Make it your own <Plus size={13}/></button>}</div></section>
 <section className="workspace"><div className="workspace-title"><div><h1>{title}<span>{count}</span></h1><p>{view==='open'?'Keep what you need. Park the rest.':view==='recent'?'A safety net for tabs Squeeze could observe.':'A quieter browser. Everything still here.'}</p></div>{filter&&<button className="icon-button" aria-label="Edit group" onClick={()=>{const n=store.categories.concat(store.sessions).find(x=>x.id===filter);setDialog({type:store.categories.some(x=>x.id===filter)?'category':'session',id:filter,name:n?.name||''})}}><MoreHorizontal size={18}/></button>}</div>
 <div className="toolbar"><label className="inline-search"><Search size={14}/><input ref={searchRef} placeholder="Search this view" aria-label="Search tabs" value={q} onChange={e=>setQ(e.target.value)}/></label><button className="text-button" onClick={()=>setSelected(new Set(selected.size?[]:(view==='open'?open.map(t=>String(t.id)):saved.map(t=>t.id))))}>{selected.size?'Deselect':'Select all'}</button></div>
 {error&&<div className="notice error" role="alert">{error}<button onClick={()=>void refresh()}>Retry</button></div>}
 {status&&<div className="notice" role="status"><CheckCircle2 size={15}/><span>{status}</span>{undo.length>0&&<button onClick={()=>{void act({type:'restore',records:undo},'Saved tabs restored.');setUndo([])}}>Undo</button>}</div>}
 {view==='sessions'&&!filter?<div className="sessions">{store.sessions.map(s=><button className="session-card" key={s.id} onClick={()=>choose('parked',s.id)}><Layers size={22}/><span><strong>{s.name}</strong><small>{store.parked.filter(t=>t.sessionId===s.id).length} tabs · Saved by you</small></span><ArrowUpRight size={18}/></button>)}<button className="create-session" onClick={()=>setDialog({type:'session',name:''})}><Plus size={16}/>Create session</button></div>:<>
 {view==='open'&&<div className="window-actions"><button className="chip" disabled={busy} onClick={()=>setSelected(new Set(tabs.filter(t=>t.windowId===data.currentWindowId).map(t=>String(t.id))))}>Current window <span>{tabs.filter(t=>t.windowId===data.currentWindowId).length}</span></button><button className="chip" disabled={busy} onClick={()=>squeeze(tabs.map(t=>t.id))}>Squeeze all <Archive size={13}/></button></div>}
 <div className="date-label">{view==='open'?'IN YOUR BROWSER':view==='recent'?'RECENTLY CLOSED':'SAVED ON THIS DEVICE'}</div>
 <motion.div layout={!reduced} className="tab-list"><AnimatePresence initial={false}>{(view==='open'?open:saved).map((tab)=>{const t=tab as SavedTab&LiveTab;const id=String(t.id);const checked=selected.has(id);const isLive=view==='open';const category=store.categories.find(c=>c.id===t.categoryId);return <motion.article key={id} layout={!reduced} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} exit={{opacity:0,scale:reduced?1:.95}} transition={{type:'spring',stiffness:350,damping:32}} className={checked?'tab-card selected':'tab-card'}>
 <button className="select-tab" role="checkbox" aria-checked={checked} aria-label={`Select ${t.title}`} onClick={()=>toggle(id)}>{checked?<Check size={12}/>:null}</button><div className="favicon" aria-hidden="true">{domain(t.url).slice(0,1).toUpperCase()}</div><div className="tab-details"><button className="tab-title" onClick={()=>isLive?toggle(id):void act({type:'reopen',ids:[id]})}>{t.title}</button><div className="tab-meta"><span>{domain(t.url)}</span>{t.pinned&&<Pin size={11}/>}<span className="meta-dot">·</span><span>{isLive?`Window ${t.windowId}`:category?.name||t.group?.title||'Uncategorized'}</span></div></div>
 {!isLive&&<button className={t.starred?'icon-button starred':'icon-button hover-action'} aria-label={t.starred?'Unstar tab':'Star tab'} onClick={()=>void act({type:'update',ids:[id],patch:{starred:!t.starred}},t.starred?'Unstarred.':'Starred.')}><Star size={14} fill={t.starred?'currentColor':'none'}/></button>}
 <button className="icon-button" aria-label={`Actions for ${t.title}`} onClick={()=>setMenu(menu===id?null:id)}><MoreHorizontal size={17}/></button>
 {menu===id&&<div className="card-menu"><div className="menu-head"><span>Tab actions</span><button aria-label="Close menu" onClick={()=>setMenu(null)}><X size={12}/></button></div>{isLive?<><button onClick={()=>{squeeze([t.id as unknown as number]);setMenu(null)}}><Archive size={14}/>Squeeze this tab</button>{t.group&&<button onClick={()=>{setSelected(new Set(tabs.filter(v=>v.group?.id===t.group?.id).map(v=>String(v.id))));setMenu(null)}}><Layers size={14}/>Select Chrome group</button>}</>:<><button onClick={()=>{void act({type:'reopen',ids:[id]});setMenu(null)}}><ArrowUpRight size={14}/>Reopen</button><button onClick={()=>{void act({type:'reopen',ids:[id],newWindow:true});setMenu(null)}}><ExternalLink size={14}/>Open in new window</button><label>Category<select aria-label="Change category" value={t.categoryId||''} onChange={e=>void act({type:'update',ids:[id],patch:{categoryId:e.target.value||null}},'Category changed.')}><option value="">Uncategorized</option>{store.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Session<select aria-label="Change session" value={t.sessionId||''} onChange={e=>void act({type:'update',ids:[id],patch:{sessionId:e.target.value||null}},'Session changed.')}><option value="">No session</option>{store.sessions.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button onClick={()=>{deleteTabs([t]);setMenu(null)}}><Trash2 size={14}/>Delete saved copy</button></>}<button onClick={()=>{void navigator.clipboard.writeText(t.url).then(()=>setStatus('URL copied.')).catch(()=>setError('Clipboard unavailable.'));setMenu(null)}}><Copy size={14}/>Copy URL</button><a href={t.url} target="_blank" rel="noreferrer" title={t.url}>View URL <ArrowUpRight size={13}/></a></div>}
 </motion.article>})}</AnimatePresence></motion.div>
 {count===0&&<div className="empty"><div className="empty-mark"><Mark/></div><h2>{q?'Nothing matches yet.':view==='open'?'A little room to breathe.':'Nothing squeezed yet.'}</h2><p>{q?'Try a title, domain, or category.':'Your browser is already pretty clean. When you want to close something without losing it, squeeze it.'}</p><button className="text-button" onClick={()=>choose('open')}>See open tabs <ArrowUpRight size={14}/></button></div>}
 </>}
 </section>
 <footer className="bottom"><span className="local-dot"/>Local by design.<span className="footer-right">No accounts. No cloud.</span></footer>
 {selected.size>0&&<div className="selection-bar"><span>{selected.size} selected</span>{view==='open'?<button className="primary" disabled={busy} onClick={()=>squeeze([...selected].map(Number))}><Archive size={15}/>{busy?'Saving...':`Squeeze ${selected.size}`}</button>:<><button className="icon-button" aria-label="Delete selected" disabled={busy} onClick={()=>deleteTabs(saved.filter(t=>selected.has(t.id)))}><Trash2 size={16}/></button><button className="primary" disabled={busy} onClick={()=>void act({type:'reopen',ids:[...selected]})}>Reopen <ArrowUpRight size={15}/></button></>}</div>}
 {filter&&saved.length>0&&selected.size===0&&<div className="selection-bar"><span>{saved.length} tabs, one place.</span><button className="primary" disabled={busy} onClick={()=>void act({type:'reopen',ids:saved.map(t=>t.id)})}>Reopen all <ArrowUpRight size={15}/></button></div>}
 <AnimatePresence>{palette&&<motion.div className="overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setPalette(false)}><motion.div className="palette" role="dialog" aria-modal="true" aria-label="Command palette" initial={{scale:reduced?1:.97,y:-8}} animate={{scale:1,y:0}} onClick={e=>e.stopPropagation()}><div className="palette-search"><Command size={17}/><span>What would you like to do?</span><button aria-label="Close command palette" onClick={()=>setPalette(false)}><X size={15}/></button></div>{[['Open tabs',()=>choose('open')],['Search squeezed',()=>{choose('parked');setTimeout(()=>searchRef.current?.focus(),0)}],['Squeeze current window',()=>squeeze(tabs.filter(t=>t.windowId===data.currentWindowId).map(t=>t.id))],['Squeeze all tabs',()=>squeeze(tabs.map(t=>t.id))],['Squeeze selected tabs',()=>squeeze([...selected].map(Number).filter(Number.isFinite))],['Open last session',()=>{const s=store.sessions.at(-1);if(s)void act({type:'reopen',ids:store.parked.filter(t=>t.sessionId===s.id).map(t=>t.id)})}],['Create session',()=>setDialog({type:'session',name:''})],['Create category',()=>setDialog({type:'category',name:''})],['About & shortcuts',()=>setHelp(true)]].map(([label,fn])=><button key={String(label)} className="palette-item" onClick={()=>{(fn as ()=>void)();setPalette(false)}}><span>{String(label)}</span><ArrowUpRight size={14}/></button>)}<div className="palette-footer">Tab to navigate · Enter to select · Esc to close</div></motion.div></motion.div>}</AnimatePresence>
 {dialog&&<div className="overlay" onClick={()=>setDialog(null)}><form className="dialog" role="dialog" aria-modal="true" aria-label={`${dialog.id?'Edit':'Create'} ${dialog.type}`} onClick={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();void act({...dialog,type:dialog.type},'Saved.');setDialog(null)}}><h2>{dialog.id?'Edit':'Create'} {dialog.type}</h2><p>A place for tabs that belong together.</p><input autoFocus required maxLength={80} placeholder="Give it a name" aria-label="Name" value={dialog.name} onChange={e=>setDialog({...dialog,name:e.target.value})}/><div className="dialog-actions">{dialog.id&&<button type="button" className="danger" onClick={()=>{void act({...dialog,remove:true},'Group removed. Tabs kept.');choose('parked');setDialog(null)}}>Remove</button>}<button type="button" onClick={()=>setDialog(null)}>Cancel</button><button className="primary" disabled={!dialog.name.trim()}>Save</button></div></form></div>}
 {help&&<div className="overlay" onClick={()=>setHelp(false)}><div className="dialog" role="dialog" aria-modal="true" aria-label="About Squeeze" onClick={e=>e.stopPropagation()}><Mark/><h2>Less clutter. Nothing lost.</h2><p>Tab metadata stays on this device. No AI, accounts, analytics, or cloud.</p><p>URLs and titles are saved, not form contents, page history, or scroll positions. Only regular web tabs can be parked.</p><p>Recently closed is best effort for observed tabs, up to 100 records. Parked tabs never auto-expire.</p><p>Palette: Ctrl / ⌘ K<br/>Chrome shortcuts: chrome://extensions/shortcuts</p><button className="primary" onClick={()=>setHelp(false)}>Back to my tabs</button></div></div>}
 </main>;
}
