import {chromium} from '@playwright/test';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
const root=path.resolve('dist');
const server=createServer(async(req,res)=>{try{const p=path.join(root,new URL(req.url,'http://localhost').pathname);const data=await readFile(p);res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.png')?'image/png':p.endsWith('.woff2')?'font/woff2':'text/html');res.end(data)}catch{res.writeHead(404);res.end()}}).listen(4173);
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:390,height:1000},deviceScaleFactor:2});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:4173/sidepanel.html');await page.getByRole('heading',{name:'Squeezed'}).waitFor();
await page.screenshot({path:'docs/screenshots/sidepanel.png',fullPage:true});
await page.getByRole('button',{name:'Open tabs',exact:false}).first().click();
await page.getByRole('article').filter({hasText:'Window 1'}).getByRole('checkbox',{name:'Select React Server Components'}).click();
await page.getByRole('button',{name:'Squeeze 1',exact:true}).click();await page.getByRole('status').waitFor();
await page.screenshot({path:'docs/screenshots/open-tabs.png',fullPage:true});
await page.keyboard.press('Control+k');await page.getByRole('dialog',{name:'Command palette'}).waitFor();await page.screenshot({path:'docs/screenshots/palette.png',fullPage:true});await page.keyboard.press('Escape');
await page.setViewportSize({width:360,height:900});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Narrow panel has horizontal overflow');
await page.setViewportSize({width:1280,height:900});await page.goto('http://localhost:4173/app.html');await page.getByRole('heading',{name:'Squeezed'}).waitFor();await page.screenshot({path:'docs/screenshots/full-app.png',fullPage:true});
await page.setViewportSize({width:360,height:900});await page.goto('http://localhost:4173/popup.html');await page.getByRole('button',{name:'Squeeze all tabs'}).waitFor();await page.locator('.popup').screenshot({path:'docs/screenshots/popup.png'});
await page.getByRole('button',{name:'Squeeze all tabs'}).click();await page.getByRole('status').waitFor();
if(errors.length)throw new Error(errors.join('\n'));
console.log('UI: saved view, open selection/squeeze, palette, 360px no overflow, popup squeeze passed.');
await browser.close();server.close();
