import {useEffect,useState} from 'react';
import {AnimatePresence,motion,useReducedMotion} from 'motion/react';
import {createRoot} from 'react-dom/client';
import {Archive,ArrowUpRight,ShieldCheck} from 'lucide-react';
import {Mark} from './components/Mark';
import {openApp,preview,request} from './lib/client';
import type {Overview,Result} from './types';
import './styles.css';
function Popup(){const reduced=useReducedMotion();const[d,setD]=useState<Overview>();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');useEffect(()=>{void request<Overview>({type:'list'}).then(setD).catch(e=>setMsg(e.message))},[]);async function squeeze(){if(!d)return;setBusy(true);try{const r=await request<Result>({type:'squeeze',tabIds:d.tabs.map(t=>t.id)});setMsg(r.message);setD(await request<Overview>({type:'list'}))}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}return <main className="popup"><header className="brand"><span className="brand-name"><Mark/>Squeeze</span><span className="version">0.1</span></header>{preview&&<div className="preview">Design preview · Sample tabs</div>}<section className="popup-hero"><span className="eyebrow">A LITTLE ROOM TO BREATHE</span><h1><AnimatePresence mode="popLayout" initial={false}><motion.span className="tab-number" key={d?.tabs.length} initial={{opacity:0,y:reduced?0:8,filter:reduced?'none':'blur(3px)'}} animate={{opacity:1,y:0,filter:'blur(0px)'}} exit={{opacity:0,y:reduced?0:-8,filter:reduced?'none':'blur(3px)'}} transition={{duration:reduced?0:.18,ease:[.2,.8,.2,1]}}>{d?.tabs.length??'…'}</motion.span></AnimatePresence><span>tabs open</span></h1><p>Close the tabs. Keep the possibilities.</p><button className="primary squeeze-main" disabled={busy||!d?.tabs.length} onClick={()=>void squeeze()}><Archive size={17}/>{busy?'Saving, then closing...':'Squeeze all tabs'}<span>↗</span></button></section><div className="popup-stats"><div><span>Current window</span><strong>{d?.tabs.filter(t=>t.windowId===d.currentWindowId).length??'…'}</strong></div><div><span>Safely squeezed</span><strong>{d?.store.parked.length??'…'}</strong></div></div><AnimatePresence>{msg&&<motion.div className="notice" role="status" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={{duration:reduced?0:.18}}>{msg}</motion.div>}</AnimatePresence><button className="open-panel" onClick={()=>void openApp().catch(e=>setMsg(e.message))}>Open Squeeze <ArrowUpRight size={17}/></button><footer className="popup-footer"><ShieldCheck size={12}/> Saved on your device. Always.</footer></main>}
createRoot(document.getElementById('root')!).render(<Popup/>);
